### ISSUE TITLE
cannot install package

### ISSUE THREAD

**Issue by mooru** [mbourqui/django-dynamic-formset#6]
pip install django-formset-bootstrap returns this error
 Could not find a version that satisfies the requirement django-formset-bootstrap (from versions: )
No matching distribution found for django-formset-bootstrap

**Comment by mbourqui** [comment]
Indeed, it looks like this package got lost during the migration of PyPI. I will upload it again later today, will let you know when it is available.

**Comment by mbourqui** [comment]
Here you are!
Let me know if you have any further issue.
